# Test of neural network
By: Magnus Kvåle Helliesen

In [1]:
import numpy as np
from neural_network.neural_network import NeuralNetwork

## Setting up a random neural network

In [2]:
nn = NeuralNetwork(100, 1000, 3, 2)

## Testing if it learns from only updating the output layer

In [3]:
# Generating a random input array
random_array1 = -0.5+np.random.random(100)
random_array2 = -0.5+np.random.random(100)

In [4]:
# Without training the neural network does not know how that maps to an output
nn.predict(random_array1)

array([0.50343231, 0.4969273 ])

In [5]:
nn.predict(random_array2)

array([0.50343232, 0.4969273 ])

In [6]:
# Let's train it (I've only written updating of output weights and bias)
nn.train(random_array1, np.array([1, 0]), 0.1)
nn.train(random_array2, np.array([0, 1]), 0.1)

In [7]:
# It already shows improvement
nn.predict(random_array1)

array([0.80677495, 0.60361615])

In [8]:
nn.predict(random_array2)

array([0.80677497, 0.60361616])