# Test of neural network
By: Magnus Kvåle Helliesen

In [1]:
import numpy as np
from neural_network.neural_network import NeuralNetwork

## Setting up a random neural network

In [2]:
nn = NeuralNetwork(100, 10000, 2, 2)

## Testing if it learns from only updating the output layer

In [3]:
# Generating a random input array
random_array1 = np.linspace(0, 1, 100)
random_array2 = np.linspace(1, 0, 100)

In [4]:
# Without training the neural network does not know how that maps to an output
nn.predict(random_array1)

IndexError: Input must have 100 rows, not 10000

In [5]:
nn.predict(random_array2)

array([0.49962152, 0.50037848])

In [7]:
# Let's train it (I've only written updating of output weights and bias)
nn.train(random_array1, np.array([1, 0]), 0.1)
nn.train(random_array2, np.array([0, 1]), 0.1)

In [8]:
# It already shows improvement
nn.predict(random_array1)

array([0.47780263, 0.52219737])

In [10]:
nn.predict(random_array2)

array([0.47526881, 0.52473119])