# Test of neural network
By: Magnus Kvåle Helliesen

In [10]:
import numpy as np
import matplotlib.pyplot as plt
from neural_network.neural_network import NeuralNetwork

## Setting up a random neural network

In [11]:
nn = NeuralNetwork(2, 500, 2, 2)

## Testing if it learns from only updating the output layer

In [12]:
# Generating a random input array
random_array1 = np.array([0,1])
random_array2 = np.array([1,0])

In [13]:
# Without training the neural network does not know how that maps to an output
nn.predict(random_array1)

array([0.49957927, 0.50042073])

In [14]:
nn.predict(random_array2)

array([0.49956721, 0.50043279])

In [15]:
# Let's train it (I've only written updating of output weights and bias)
for _ in range(10):
    nn.train(((random_array1, np.array([1, 0])), (random_array2, np.array([0, 1]))), 0.1)

In [16]:
# It already shows improvement
nn.predict(random_array1)

array([1.3194379e-188, 1.0000000e+000])

In [17]:
nn.predict(random_array2)

array([2.32817171e-189, 1.00000000e+000])

In [21]:
plt.contour(nn.weights[2])

IndexError: list index out of range