# Test of neural network
By: Magnus Kvåle Helliesen

In [1]:
import numpy as np
from neural_network.neural_network import NeuralNetwork

In [2]:
nn = NeuralNetwork(100, 100, 3, 2)

In [3]:
random_array = -0.5+np.random.random(100)

In [4]:
nn.predict(random_array)

array([0.5, 0.5])

In [5]:
nn.train(random_array, np.array([1, 0]))

In [6]:
nn.predict(random_array)

array([0.96267311, 0.03732689])

In [7]:
nn.b_o

array([ 0.125, -0.125])

In [8]:
nn.w_o

array([[ 0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
      