# Test of neural network
By: Magnus Kvåle Helliesen

In [1]:
import numpy as np
from neural_network.neural_network import NeuralNetwork

## Setting up a random neural network

In [2]:
nn = NeuralNetwork(2, 4, 2, 2)

## Testing if it learns from only updating the output layer

In [3]:
# Generating a random input array
random_array1 = np.linspace(0, 1, 2)
random_array2 = np.linspace(1, 0, 2)

In [4]:
# Without training the neural network does not know how that maps to an output
nn.predict(random_array1)

array([0.50348784, 0.49651216])

In [5]:
nn.predict(random_array2)

array([0.49641568, 0.50358432])

In [16]:
# Let's train it (I've only written updating of output weights and bias)
nn.train(((random_array1, np.array([1, 0])), (random_array2, np.array([0, 1]))), 1)

[[ 0.          0.          0.00124099  0.        ]
 [-0.         -0.         -0.00124099 -0.        ]]
[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.14675458 -0.         -0.09002905 -0.11847936]
 [ 0.          0.          0.          0.        ]]


In [17]:
# It already shows improvement
nn.predict(random_array1)

array([0.51153484, 0.48846516])

In [18]:
nn.predict(random_array2)

array([0.49582273, 0.50417727])

In [9]:
a = ((np.ones(3), np.ones(2)), (np.ones(3), np.ones(2)))

In [10]:
sum(x[1] for x in a)

array([2., 2.])