# Test of neural network
By: Magnus Kvåle Helliesen

In [1]:
import numpy as np
from neural_network.neural_network import NeuralNetwork

## Setting up a random neural network

In [13]:
nn = NeuralNetwork(100, 1000, 3, 2)

## Testing if it learns from only updating the output layer

In [14]:
# Generating a random input array
random_array1 = np.linspace(0, 1, 100)
random_array2 = np.linspace(1, 0, 100)

In [15]:
# Without training the neural network does not know how that maps to an output
nn.predict(random_array1)

array([0.49882241, 0.49161833])

In [16]:
nn.predict(random_array2)

array([0.49882241, 0.49161832])

In [29]:
# Let's train it (I've only written updating of output weights and bias)
nn.train(random_array1, np.array([1, 0]), 0.1)
nn.train(random_array2, np.array([0, 1]), 0.1)

In [30]:
# It already shows improvement
nn.predict(random_array1)

array([1.57564867e-04, 5.82946099e-01])

In [31]:
nn.predict(random_array2)

array([1.57564902e-04, 5.82946089e-01])